### ISSUE TITLE
I don't think code for calculating SNAP inside the model object works properly

### ISSUE THREAD

**Issue by josephmullins** [josephmullins/welfare-meta-study#9]
Example: Mod1.SNAP[1,1,1,1,1,1,1,1] = $657. It should be zero?

I think this could be messing up calculations of simulated Food Stamps.

**Comment by filbabalievsky1** [comment]
Whoops! There was a typo in Budget_Function_Code.jl. On line 201, it should have multiplied Foodstamps by "Program" (the 0-1 indicator for program participation) before storing it in Foodstamps_Receipt. I have pushed the change, which resolves the specific example you mentioned.
